### ISSUE TITLE
Please use native PHP reflection

### ISSUE THREAD

**Issue by peterdutton** [heiglandreas/htmltopdflib#3]
Hi,

Thanks again for the great library! 

We have been testing it and have come across some performance issues, which we suspect could be down to the use of `roave/better-reflection`. Their project appears not to be focused on production use, as [their readme](https://github.com/Roave/BetterReflection#user-content-why-is-it-better:~:text=Better%20Reflection%20is%20NOT%20suited%20to,Reflection%20refers%20to%20feature%2C%20not%20speed!) states:

> Better Reflection is NOT suited to runtime usage, since performance is much worse than PHP built-in reflection. If you do not want to do anything that native PHP reflection can't do, then just use native PHP reflection! The "Better" in Better Reflection refers to feature, not speed!

As it doesn't seem to need any of the special features of `better-reflection` would it be possible to implement natively instead?

I believe the only two changes would be for the following line could be removed:
https://github.com/heiglandreas/htmltopdflib/blob/efd84aaac98ac76f8a43e15ffc5e5a6f6737600c/src/ConverterList.php#L13

And this line just below to use ` $class = new ReflectionClass($converter);`:
https://github.com/heiglandreas/htmltopdflib/blob/efd84aaac98ac76f8a43e15ffc5e5a6f6737600c/src/ConverterList.php#L30 

I hope this sounds OK to you. Thanks!

**Comment by heiglandreas** [comment]
Well, it is intended for production use but not during runtime but more during chace warmup or CodeGeneration like for Proxies or things like that.

Anyway. I have modified the code a bit to use two separate named constructors, one for people that want to use BetterReflection (due to that class not actually loading the class into PHP for doing the reflection stuff) and one for people that want to use the native Reflection implementation. By default the native implementation will be used.

Would you mind giving #4 a short Review whether that matches your expectations?

*Caveat:* Due to the named constructors the Constructor for the ConverterList became private which is a breaking change. So this will result in a version 2 of the lib.

**Comment by heiglandreas** [comment]
Oh. The reason why I went for BetterReflection in the first place was, that it doesn't load the classes into PHP when using the Reflection which is what the default Reflection does. At that point I thought it would be a good idea to only load the classes that you are actually using when they get instantiated. So as long as you are only loading the default classes using the default reflection is definitely the easier choice. That might become different at one point when you need to load much more classes or more complex classes. That's why I left the BetterReflection as an option but use Reflection now for the defaults.

**Comment by peterdutton** [comment]
Hi @heiglandreas - thanks for looking into this so quickly! I looked at the code - seems like a really nice solution allowing the best of both worlds. Thanks again :smiley:

**Comment by heiglandreas** [comment]
Version 2.0.0 has been tagged. Thanks for raising the issue!

**Comment by peterdutton** [comment]
Just got chance to test this - thanks again @heiglandreas  :smiley:
